HELP_TEXT = ["FM Explorer - find interesting parameters for FM synthesis              by Andrew T. Smith (2023)",
             '--------------------------------------------------------------',
             ' ',
             '  FM(t) = A(t) * sin [2 * pi * Fc(t) * t + D(t) * sin(2 * pi * Fm(t) * t)]',
             '           ------------------   ------------------',
             '           Carrier                          Modulation',
             ' ',
             '    * A(t) = carrier amplitude, Fc(t) = carrier frequency',
             '    * D(t) = modulation depth,  Fm(t) = modulation frequency',
             ' ',
             ' Instructions:',
             '     -->  Move mouse to change params.',
             '     -->  Hit space to start / stop sound.',
             ' ',
             '  All hotkeys:',
             '      h - Help screen on / off.',
             "     ' ' -  Play Sound / Stop Sound",
             ' ',
             "     a  -  toggle autotune (theremin mode only)",
             "    t,c -  select Theremin mode / Carrier mode.",
             "     x  -  toggle modulation freq scaling to preserve timbre on/off.",
             "     b  -  toggle note-area guid box (theremin mode).",
             "     .  -  FFT window smaller",
             "     ,  -  FFT window larger"
             "     q  -  Quit                           ",
             ' ',
             '   Mouseover window to adjust axis with hotkeys (some are locked):',
             "     0  -  adjust vertical axis range up",
             "     p  -  adjust vertical axis range down",
             "     ]  -  adjust horizontal axis range up",
             "     [  -  adjust horizontal axis range down",
             ' ',
             ]
