HELP_TEXT = ["FM Explorer - find interesting parameters for FM synthesis",
             '-----------------------------------------------------------',
             ' ',
             '  FM(t) = A(t) * sin[2 * pi * Fc(t) * t + D(t) * sin(2 * pi * Fm(t) * t)]',
             ' ',
             ' ',
             '    * carrier:  A(t) = amplitude, Fc(t) = frequency',
             '    * modulation:   D(t) = depth,  Fm(t) = mod. frequency',
             ' ',
             '     -->  Move mouse to change these params',
             ' ',
             '  Hotkeys:',
             ' ',
             "     ' ' toggle grid:  Carrier / Modulation",
             "     h - toggle this help screen"
             "     s - save current modulation params (unimplemented)",
             "     q - Quit",
             ' ',
             "     0 - adjust vertical axis range up",
             "     p - adjust vertical axis range down",
             ' ',
             "     ] - adjust horizontal axis range up",
             "     [ - adjust horizontal axis range down",
             ' ',
             "     . - waveform zoom in",
             "     , - waveform zoom out"
             ]
