HELP_TEXT = ["FM Explorer - find interesting parameters for FM synthesis                     by Andrew T. Smith (2023)",
             '------------------------------------------------------------------',
             ' ',
             '  FM(t) = A(t) * sin [2 * pi * Fc(t) * t + D(t) * sin(2 * pi * Fm(t) * t)]',
             '          ------------------   ------------------',
             '           Carrier                           Modulation',
             ' ',
             '    * A(t) = carrier amplitude, Fc(t) = carrier frequency',
             '    * D(t) = modulation depth,  Fm(t) = modulation frequency',
             ' ',
             ' Instructions:',
             '     -->  Move mouse to change params.',
             '     -->  Hit space to start / stop sound.',
             '     -->  Hit M or C or T to change modes (Modulation / Carrier / Theremin)',
             ' ',
             '  All hotkeys:',
             "     ' ' -  Play Sound / Stop Sound                                h  - Help screen on / off.",
             "     p  -  Timbre preserving carrier freq adjust on/off.",
             "     c, m, t -  Toggle mode",
             "     s  -  save current modulation params",
             "     q  -  Quit                           ",
             ' ' ,
             "     0  -  adjust vertical axis range up (some axes are locked)",
             "     p  -  adjust vertical axis range down",
             ' ',
             "     ]  -  adjust horizontal axis range up",
             "     [  -  adjust horizontal axis range down",
             ' ',
             "     .  -  FFT window smaller",
             "     ,  -  FFT window larger"
             ]
